input {
    file{
        path => "/logs/app.log"
        start_position => "end"
        sincedb_path => "/usr/share/logstash/data/.sincedb_livros"
    }
}

filter {
    json {
        source => "message"
    }

    if "_jsonparsefailure" in [tags] {
        drop { }
    }

    mutate {
        remove_field => ["message", "event", "host", "log", "@version", "tags"]
    }
}

output {
    elasticsearch{
        hosts => ["http://elasticsearch:9200"]
        index => "livros-logs"
    }
    stdout{
        codec => rubydebug
    }
}